name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zebux/docker_nmap:latest
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Publish the Docker image in DockerHub
      run: |
    #    docker login -u zebux -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push zebux/docker_nmap:latest
